name: Clojure CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 1.11.1.1224
      - uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: "2023.02.17"
      - name: lint
        run: clj-kondo --lint src
      - name: Run tests
        run: clojure -M:test

  antq:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: antq
        uses: liquidz/antq-action@main
